spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/akilani/eks-blueprints-workloads # This will be surcharged by our Terraform workload_application.values.spec.source.repoURL variable.
    targetRevision: main
